name: Backend Deploy to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'  # backend 폴더의 변경사항이 있을 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'  # Maven 캐시 활성화
        
    - name: Build with Maven
      run: |
        cd backend
        mvn clean package -DskipTests  # 테스트 스킵하고 빌드
        
    - name: Copy files to EC2 with SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "backend/target/*.jar"  # Maven은 target 폴더에 빌드 결과물 생성
        target: "/home/ec2-user/app"
        strip_components: 2
        
    - name: Execute deploy script on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/app
          ./deploy.sh 